In [1]:
!pip3 install nltk

Requirement already satisfied: nltk in /opt/anaconda3/lib/python3.14/site-packages (3.10.0)
Requirement already satisfied: defusedxml in /opt/anaconda3/lib/python3.14/site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in /opt/anaconda3/lib/python3.14/site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /opt/anaconda3/lib/python3.14/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /opt/anaconda3/lib/python3.14/site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.14/site-packages (from nltk) (4.68.2)

In [2]:
import numpy as np
import pandas as pd
import re
import nltk
import string

full_df = pd.read_csv('tweet_small.csv')

In [3]:
full_df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregar...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,@105835 Your business means a lot to us. Pleas...,NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm su...,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - htt...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've...,119243,119240.0

In [4]:
df = full_df[['text']]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    93 non-null     str
dtypes: str(1)
memory usage: 11.7 KB

In [7]:
df

                                                 text
0   @AppleSupport causing the reply to be disregar...
1   @105835 Your business means a lot to us. Pleas...
2   @76328 I really hope you all change but I'm su...
3   @105836 LiveChat is online at the moment - htt...
4   @VirginTrains see attached error message. I've...
..                                                ...
88  @105860 I wish Amazon had an option of where I...
89  They reschedule my shit for tomorrow https://t...
90  @105861 Hey Sara, sorry to hear of the issues ...
91  @Tesco bit of both - finding the layout cumber...
92  @105861 If that doesn't help please DM your fu...

[93 rows x 1 columns]

### Переход к нижнему регистру

In [9]:
df['text_lower'] = df['text'].str.lower()
df

,text,text_lower
0,@AppleSupport causing the reply to be disregar...,@applesupport causing the reply to be disregar...
1,@105835 Your business means a lot to us. Pleas...,@105835 your business means a lot to us. pleas...
2,@76328 I really hope you all change but I'm su...,@76328 i really hope you all change but i'm su...
3,@105836 LiveChat is online at the moment - htt...,@105836 livechat is online at the moment - htt...
4,@VirginTrains see attached error message. I've...,@virgintrains see attached error message. i've...
...,...,...
88,@105860 I wish Amazon had an option of where I...,@105860 i wish amazon had an option of where i...
89,They reschedule my shit for tomorrow https://t...,they reschedule my shit for tomorrow https://t...
90,"@105861 Hey Sara, sorry to hear of the issues ...","@105861 hey sara, sorry to hear of the issues ..."
91,@Tesco bit of both - finding the layout cumber...,@tesco bit of both - finding the layout cumber...
92,@105861 If that doesn't help please DM your fu...,@105861 if that doesn't help please dm your fu...

### Удаление пунктуации

In [10]:
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

df['text_wo_punct'] = df['text_lower'].apply(remove_punctuation)
df

,text,text_lower,text_wo_punct
0,@AppleSupport causing the reply to be disregar...,@applesupport causing the reply to be disregar...,applesupport causing the reply to be disregard...
1,@105835 Your business means a lot to us. Pleas...,@105835 your business means a lot to us. pleas...,105835 your business means a lot to us please ...
2,@76328 I really hope you all change but I'm su...,@76328 i really hope you all change but i'm su...,76328 i really hope you all change but im sure...
3,@105836 LiveChat is online at the moment - htt...,@105836 livechat is online at the moment - htt...,105836 livechat is online at the moment https...
4,@VirginTrains see attached error message. I've...,@virgintrains see attached error message. i've...,virgintrains see attached error message ive tr...
...,...,...,...
88,@105860 I wish Amazon had an option of where I...,@105860 i wish amazon had an option of where i...,105860 i wish amazon had an option of where i ...
89,They reschedule my shit for tomorrow https://t...,they reschedule my shit for tomorrow https://t...,they reschedule my shit for tomorrow httpstcor...
90,"@105861 Hey Sara, sorry to hear of the issues ...","@105861 hey sara, sorry to hear of the issues ...",105861 hey sara sorry to hear of the issues yo...
91,@Tesco bit of both - finding the layout cumber...,@tesco bit of both - finding the layout cumber...,tesco bit of both finding the layout cumberso...
92,@105861 If that doesn't help please DM your fu...,@105861 if that doesn't help please dm your fu...,105861 if that doesnt help please dm your full...

### Удаление стоп-слов

In [11]:
from nltk.corpus import stopwords
nltk.download('stopwords')
', '.join(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/artemgolubnichiy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

"a, about, above, after, again, against, ain, all, am, an, and, any, are, aren, aren't, as, at, be, because, been, before, being, below, between, both, but, by, can, couldn, couldn't, d, did, didn, didn't, do, does, doesn, doesn't, doing, don, don't, down, during, each, few, for, from, further, had, hadn, hadn't, has, hasn, hasn't, have, haven, haven't, having, he, he'd, he'll, her, here, hers, herself, he's, him, himself, his, how, i, i'd, if, i'll, i'm, in, into, is, isn, isn't, it, it'd, it'll, it's, its, itself, i've, just, ll, m, ma, me, mightn, mightn't, more, most, mustn, mustn't, my, myself, needn, needn't, no, nor, not, now, o, of, off, on, once, only, or, other, our, ours, ourselves, out, over, own, re, s, same, shan, shan't, she, she'd, she'll, she's, should, shouldn, shouldn't, should've, so, some, such, t, than, that, that'll, the, their, theirs, them, themselves, then, there, these, they, they'd, they'll, they're, they've, this, those, through, to, too, under, until, up, ve, very, was, wasn, wasn't, we, we'd, we'll, we're, were, weren, weren't, we've, what, when, where, which, while, who, whom, why, will, with, won, won't, wouldn, wouldn't, y, you, you'd, you'll, your, you're, yours, yourself, yourselves, you've"

In [13]:
STOPWORDS = set(stopwords.words('english'))

def remove_stopwords(text):
    return ' '.join([word for word in str(text).split(' ') if word not in STOPWORDS])

df['text_wo_stop'] = df['text_wo_punct'].apply(remove_stopwords)

df

,text,text_lower,text_wo_punct,text_wo_stop
0,@AppleSupport causing the reply to be disregar...,@applesupport causing the reply to be disregar...,applesupport causing the reply to be disregard...,applesupport causing reply disregarded tapped ...
1,@105835 Your business means a lot to us. Pleas...,@105835 your business means a lot to us. pleas...,105835 your business means a lot to us please ...,105835 business means lot us please dm name zi...
2,@76328 I really hope you all change but I'm su...,@76328 i really hope you all change but i'm su...,76328 i really hope you all change but im sure...,76328 really hope change im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,@105836 livechat is online at the moment - htt...,105836 livechat is online at the moment https...,105836 livechat online moment httpstcosy94vtu...
4,@VirginTrains see attached error message. I've...,@virgintrains see attached error message. i've...,virgintrains see attached error message ive tr...,virgintrains see attached error message ive tr...
...,...,...,...,...
88,@105860 I wish Amazon had an option of where I...,@105860 i wish amazon had an option of where i...,105860 i wish amazon had an option of where i ...,105860 wish amazon option get shipped ups stor...
89,They reschedule my shit for tomorrow https://t...,they reschedule my shit for tomorrow https://t...,they reschedule my shit for tomorrow httpstcor...,reschedule shit tomorrow httpstcorsvzct982t
90,"@105861 Hey Sara, sorry to hear of the issues ...","@105861 hey sara, sorry to hear of the issues ...",105861 hey sara sorry to hear of the issues yo...,105861 hey sara sorry hear issues ask lay spee...
91,@Tesco bit of both - finding the layout cumber...,@tesco bit of both - finding the layout cumber...,tesco bit of both finding the layout cumberso...,tesco bit finding layout cumbersome removing ...
92,@105861 If that doesn't help please DM your fu...,@105861 if that doesn't help please dm your fu...,105861 if that doesnt help please dm your full...,105861 doesnt help please dm full name address...

### Удаление частых слов

In [14]:
from collections import Counter
cnt = Counter()
for text in df['text_wo_stop'].values:
    for word in text.split():
        cnt[word] += 1

cnt.most_common(10)

[('us', 25),
 ('dm', 19),
 ('help', 18),
 ('thanks', 13),
 ('httpstcogdrqu22ypt', 12),
 ('applesupport', 11),
 ('please', 11),
 ('phone', 9),
 ('hi', 9),
 ('ive', 8)]

In [15]:
FREQWORDS = set([w for (w, ws) in cnt.most_common(10)])

def remove_freqwords(text):
    return ' '.join([word for word in str(text).split(' ') if word not in FREQWORDS])

df['text_wo_stop_freq'] = df['text_wo_stop'].apply(remove_freqwords)
df

,text,text_lower,text_wo_punct,text_wo_stop,text_wo_stop_freq
0,@AppleSupport causing the reply to be disregar...,@applesupport causing the reply to be disregar...,applesupport causing the reply to be disregard...,applesupport causing reply disregarded tapped ...,causing reply disregarded tapped notification ...
1,@105835 Your business means a lot to us. Pleas...,@105835 your business means a lot to us. pleas...,105835 your business means a lot to us please ...,105835 business means lot us please dm name zi...,105835 business means lot name zip code additi...
2,@76328 I really hope you all change but I'm su...,@76328 i really hope you all change but i'm su...,76328 i really hope you all change but im sure...,76328 really hope change im sure wont dont,76328 really hope change im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,@105836 livechat is online at the moment - htt...,105836 livechat is online at the moment https...,105836 livechat online moment httpstcosy94vtu...,105836 livechat online moment httpstcosy94vtu...
4,@VirginTrains see attached error message. I've...,@virgintrains see attached error message. i've...,virgintrains see attached error message ive tr...,virgintrains see attached error message ive tr...,virgintrains see attached error message tried ...
...,...,...,...,...,...
88,@105860 I wish Amazon had an option of where I...,@105860 i wish amazon had an option of where i...,105860 i wish amazon had an option of where i ...,105860 wish amazon option get shipped ups stor...,105860 wish amazon option get shipped ups stor...
89,They reschedule my shit for tomorrow https://t...,they reschedule my shit for tomorrow https://t...,they reschedule my shit for tomorrow httpstcor...,reschedule shit tomorrow httpstcorsvzct982t,reschedule shit tomorrow httpstcorsvzct982t
90,"@105861 Hey Sara, sorry to hear of the issues ...","@105861 hey sara, sorry to hear of the issues ...",105861 hey sara sorry to hear of the issues yo...,105861 hey sara sorry hear issues ask lay spee...,105861 hey sara sorry hear issues ask lay spee...
91,@Tesco bit of both - finding the layout cumber...,@tesco bit of both - finding the layout cumber...,tesco bit of both finding the layout cumberso...,tesco bit finding layout cumbersome removing ...,tesco bit finding layout cumbersome removing ...
92,@105861 If that doesn't help please DM your fu...,@105861 if that doesn't help please dm your fu...,105861 if that doesnt help please dm your full...,105861 doesnt help please dm full name address...,105861 doesnt full name address email includin...

In [16]:
df.drop(['text_lower', 'text_wo_punct', 'text_wo_stop'], axis=1, inplace=True)

In [17]:
df

,text,text_wo_stop_freq
0,@AppleSupport causing the reply to be disregar...,causing reply disregarded tapped notification ...
1,@105835 Your business means a lot to us. Pleas...,105835 business means lot name zip code additi...
2,@76328 I really hope you all change but I'm su...,76328 really hope change im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,105836 livechat online moment httpstcosy94vtu...
4,@VirginTrains see attached error message. I've...,virgintrains see attached error message tried ...
...,...,...
88,@105860 I wish Amazon had an option of where I...,105860 wish amazon option get shipped ups stor...
89,They reschedule my shit for tomorrow https://t...,reschedule shit tomorrow httpstcorsvzct982t
90,"@105861 Hey Sara, sorry to hear of the issues ...",105861 hey sara sorry hear issues ask lay spee...
91,@Tesco bit of both - finding the layout cumber...,tesco bit finding layout cumbersome removing ...
92,@105861 If that doesn't help please DM your fu...,105861 doesnt full name address email includin...

### Удаление редких слов

In [18]:
n_rare_words = 10
RAREWORDS = set([w for (w, ws) in cnt.most_common()[:-n_rare_words:-1]])
RAREWORDS

{'browser',
 'green',
 'httpstco9281okeebk',
 'including',
 'keen',
 'lee',
 'line',
 'log',
 'thin'}

In [19]:
def remove_rarewords(text):
    return ' '.join([word for word in str(text).split(' ') if word not in RAREWORDS])

df['text_wo_stop_freq_rare'] = df['text_wo_stop_freq'].apply(remove_rarewords)
df

,text,text_wo_stop_freq,text_wo_stop_freq_rare
0,@AppleSupport causing the reply to be disregar...,causing reply disregarded tapped notification ...,causing reply disregarded tapped notification ...
1,@105835 Your business means a lot to us. Pleas...,105835 business means lot name zip code additi...,105835 business means lot name zip code additi...
2,@76328 I really hope you all change but I'm su...,76328 really hope change im sure wont dont,76328 really hope change im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,105836 livechat online moment httpstcosy94vtu...,105836 livechat online moment httpstcosy94vtu...
4,@VirginTrains see attached error message. I've...,virgintrains see attached error message tried ...,virgintrains see attached error message tried ...
...,...,...,...
88,@105860 I wish Amazon had an option of where I...,105860 wish amazon option get shipped ups stor...,105860 wish amazon option get shipped ups stor...
89,They reschedule my shit for tomorrow https://t...,reschedule shit tomorrow httpstcorsvzct982t,reschedule shit tomorrow httpstcorsvzct982t
90,"@105861 Hey Sara, sorry to hear of the issues ...",105861 hey sara sorry hear issues ask lay spee...,105861 hey sara sorry hear issues ask lay spee...
91,@Tesco bit of both - finding the layout cumber...,tesco bit finding layout cumbersome removing ...,tesco bit finding layout cumbersome removing ...
92,@105861 If that doesn't help please DM your fu...,105861 doesnt full name address email includin...,105861 doesnt full name address email device 22

### Стемминг

In [20]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

def stem_words(text):
    return ' '.join([stemmer.stem(word) for word in text.split()])

df['text_stemmed'] = df['text_wo_stop_freq_rare'].apply(stem_words)
df

,text,text_wo_stop_freq,text_wo_stop_freq_rare,text_stemmed
0,@AppleSupport causing the reply to be disregar...,causing reply disregarded tapped notification ...,causing reply disregarded tapped notification ...,caus repli disregard tap notif keyboard opened😡😡😡
1,@105835 Your business means a lot to us. Pleas...,105835 business means lot name zip code additi...,105835 business means lot name zip code additi...,105835 busi mean lot name zip code addit detai...
2,@76328 I really hope you all change but I'm su...,76328 really hope change im sure wont dont,76328 really hope change im sure wont dont,76328 realli hope chang im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,105836 livechat online moment httpstcosy94vtu...,105836 livechat online moment httpstcosy94vtu...,105836 livechat onlin moment httpstcosy94vtu8k...
4,@VirginTrains see attached error message. I've...,virgintrains see attached error message tried ...,virgintrains see attached error message tried ...,virgintrain see attach error messag tri leav v...
...,...,...,...,...
88,@105860 I wish Amazon had an option of where I...,105860 wish amazon option get shipped ups stor...,105860 wish amazon option get shipped ups stor...,105860 wish amazon option get ship up store av...
89,They reschedule my shit for tomorrow https://t...,reschedule shit tomorrow httpstcorsvzct982t,reschedule shit tomorrow httpstcorsvzct982t,reschedul shit tomorrow httpstcorsvzct982t
90,"@105861 Hey Sara, sorry to hear of the issues ...",105861 hey sara sorry hear issues ask lay spee...,105861 hey sara sorry hear issues ask lay spee...,105861 hey sara sorri hear issu ask lay speed ...
91,@Tesco bit of both - finding the layout cumber...,tesco bit finding layout cumbersome removing ...,tesco bit finding layout cumbersome removing ...,tesco bit find layout cumbersom remov item fav...
92,@105861 If that doesn't help please DM your fu...,105861 doesnt full name address email includin...,105861 doesnt full name address email device 22,105861 doesnt full name address email devic 22

In [21]:
df.drop(['text_wo_stop_freq', 'text_wo_stop_freq_rare'], axis=1, inplace=True)
df

,text,text_stemmed
0,@AppleSupport causing the reply to be disregar...,caus repli disregard tap notif keyboard opened😡😡😡
1,@105835 Your business means a lot to us. Pleas...,105835 busi mean lot name zip code addit detai...
2,@76328 I really hope you all change but I'm su...,76328 realli hope chang im sure wont dont
3,@105836 LiveChat is online at the moment - htt...,105836 livechat onlin moment httpstcosy94vtu8k...
4,@VirginTrains see attached error message. I've...,virgintrain see attach error messag tri leav v...
...,...,...
88,@105860 I wish Amazon had an option of where I...,105860 wish amazon option get ship up store av...
89,They reschedule my shit for tomorrow https://t...,reschedul shit tomorrow httpstcorsvzct982t
90,"@105861 Hey Sara, sorry to hear of the issues ...",105861 hey sara sorri hear issu ask lay speed ...
91,@Tesco bit of both - finding the layout cumber...,tesco bit find layout cumbersom remov item fav...
92,@105861 If that doesn't help please DM your fu...,105861 doesnt full name address email devic 22

In [22]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer('russian')

wrds = ['трансцендентный', 'автостеклоподъемники',  'электростеклоподъемники', 'длинношеее', 'урегулирование',
'воспользовавшийся', 'сиреневенький', 'переосвидетельствовать', 'человеконенавистничество', 'высокопревосходительство',
'защищающихся']

for w in wrds:
    print(stemmer.stem(w))

трансцендентн
автостеклоподъемник
электростеклоподъемник
длинноше
урегулирован
воспользова
сиреневеньк
переосвидетельствова
человеконенавистничеств
высокопревосходительств
защища